# Overture — Places quickstart (live)

Fetch points of interest for a small bbox and read them back. Overture Places is public and anonymous — no credentials.

In [1]:
LAT_LIM = [40.757, 40.759]  # [south, north]
LON_LIM = [-73.987, -73.984]  # [west, east] — a Times Square block
OUT = "_overture_out"

In [2]:
from earthlens.earthlens import EarthLens

paths = EarthLens(
    data_source="overture",
    dataset="places",
    variables=[],  # [] -> the theme primary type, "place"
    aoi=[LON_LIM[0], LAT_LIM[0], LON_LIM[1], LAT_LIM[1]],
    path=OUT,
).download()
paths

2026-05-27 14:47:44 | INFO | pyramids.base.config | Logging is configured.

2026-05-27 14:47:44.776 | INFO     | earthlens.overture.backend:_fetch:377 - Fetching Overture 'place' (theme 'places') for bbox (-73.987, 40.757, -73.984, 40.759) (release=latest)

2026-05-27 14:47:52.217 | INFO     | earthlens.overture.backend:_fetch:386 - places/place: wrote 519 feature(s) to C:\gdrive\algorithms\remote-sensing\earthlens\.claude\worktrees\overture\docs\examples\overture\_overture_out\overture_places_place_latest.parquet

[WindowsPath('C:/gdrive/algorithms/remote-sensing/earthlens/.claude/worktrees/overture/docs/examples/overture/_overture_out/overture_places_place_latest.parquet')]

In [3]:
import geopandas as gpd

gdf = gpd.read_parquet(paths[0])
print(len(gdf), 'places;  CRS', gdf.crs.to_epsg())
gdf[['id', 'license_id']].head()

519 places;  CRS 4326

                                     id                       license_id
0  7d193f10-8708-45fe-acb7-84e5a419d413  Apache-2.0; CDLA-Permissive-2.0
1  3cafc4f2-84b8-4b84-8757-2dc4f4da869b              CDLA-Permissive-2.0
2  f0bd5a53-ed02-4c56-9787-bdf18779ae60              CDLA-Permissive-2.0
3  b0ccaec7-07c4-4afa-a1fb-6ebc81d1c2e8              CDLA-Permissive-2.0
4  53688696-5bb1-4fe1-8209-ae8356cec963              CDLA-Permissive-2.0

Place names live in the nested `names` struct; pull the primary name out for a quick look.

In [4]:
def primary_name(names):
    if isinstance(names, dict):
        return names.get('primary')
    return None


gdf['name'] = gdf['names'].apply(primary_name)
gdf[['name', 'license_id']].dropna(subset=['name']).head(10)

                                        name                       license_id
0                            T.G.I. Friday's  Apache-2.0; CDLA-Permissive-2.0
1          Bryant Park, 5th Ave. 42nd St NY.              CDLA-Permissive-2.0
2      Tempo by Hilton New York Times Square              CDLA-Permissive-2.0
3                             Cranberry Cafe              CDLA-Permissive-2.0
4                    Beetlejuice the Musical              CDLA-Permissive-2.0
5                       Holler If Ya Hear Me              CDLA-Permissive-2.0
6  ACM - Association for Computing Machinery              CDLA-Permissive-2.0
7                           Sunset Boulevard  Apache-2.0; CDLA-Permissive-2.0
8                             Palace Theatre              CDLA-Permissive-2.0
9                               TSX Broadway              CDLA-Permissive-2.0